### ISSUE TITLE
feren-kde-settings issue

### ISSUE THREAD

**Issue by zorzgeo** [feren-OS/Feren-OS-Dependency-Issue-Reporting#13]
Trying to update through Update manager for "feren-kde-settings" with error from picture below.
![Screenshot_20200130_184505](https://user-images.githubusercontent.com/47013356/73476051-d91b8600-4391-11ea-84a4-fde2572be6c9.png)

**Comment by dominichayesferen** [comment]
The package got updated again, hit Refresh and try it again.
