### ISSUE TITLE
Broken multiple packeges related to Libreoffice (libuno-*)

### ISSUE THREAD

**Issue by gherrarte** [feren-OS/Feren-OS-Dependency-Issue-Reporting#15]
libreoffice-base : Depends: libreoffice-common (>= 1:6.4.0~beta1-2~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
                    Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                    Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
                    Depends: libuno-sal3 (>= 5.1.0~alpha) but it is not installed
                    Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                    Depends: uno-libs-private but it is not installed
                    Breaks: libreoffice-common (< 1:6.4.2~rc1~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
                    Recommends: libreoffice-java-common (>= 1:6.4.2~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
 libreoffice-base-core : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                         Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                         Depends: libuno-sal3 (>= 5.1.0~alpha) but it is not installed
                         Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                         Depends: uno-libs-private but it is not installed
 libreoffice-base-drivers : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                            Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                            Depends: libuno-sal3 (>= 5.3.0~alpha) but it is not installed
                            Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                            Depends: uno-libs-private but it is not installed
 libreoffice-calc : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                    Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
                    Depends: libuno-sal3 (>= 5.3.0~alpha) but it is not installed
                    Depends: libuno-salhelpergcc3-3 (>= 3.6.0~beta) but it is not installed
                    Depends: uno-libs-private but it is not installed
                    Breaks: libreoffice-common (< 1:6.4.2~rc1~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
 libreoffice-common : Breaks: libreoffice-core (>= 1:6.4~) but 1:6.4.2-0ubuntu0.18.04.2 is installed
                      Breaks: libreoffice-style-tango (>= 1:6.4~) but 1:6.4.2-0ubuntu0.18.04.2 is installed
 libreoffice-core : Depends: libreoffice-common (> 1:6.4.2) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
                    Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                    Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                    Depends: libuno-sal3 (>= 6.4.0~beta) but it is not installed
                    Depends: libuno-salhelpergcc3-3 (>= 3.6.0~beta) but it is not installed
                    Depends: uno-libs-private but it is not installed
 libreoffice-draw : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                    Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                    Depends: libuno-sal3 (>= 5.3.0~alpha) but it is not installed
                    Depends: libuno-salhelpergcc3-3 (>= 3.6.0~beta) but it is not installed
                    Depends: uno-libs-private but it is not installed
                    Breaks: libreoffice-common (< 1:6.4.2~rc1~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
 libreoffice-gnome : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                     Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
                     Depends: libuno-sal3 (>= 5.1.0~alpha) but it is not installed
                     Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                     Depends: uno-libs-private but it is not installed
 libreoffice-gtk3 : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                    Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
                    Depends: libuno-sal3 (>= 5.1.0~alpha) but it is not installed
                    Depends: uno-libs-private but it is not installed
 libreoffice-impress : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                       Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                       Depends: libuno-sal3 (>= 5.3.0~alpha) but it is not installed
                       Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                       Depends: uno-libs-private but it is not installed
                       Breaks: libreoffice-common (< 1:6.4.2~rc1~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
 libreoffice-math : Depends: libreoffice-core (= 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1) but 1:6.4.2-0ubuntu0.18.04.2 is installed
 libreoffice-report-builder-bin : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                                  Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
                                  Depends: libuno-sal3 (>= 5.1.0~alpha) but it is not installed
                                  Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                                  Depends: uno-libs-private but it is not installed
 libreoffice-sdbc-firebird : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                             Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                             Depends: libuno-sal3 (>= 5.1.0~alpha) but it is not installed
                             Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                             Depends: uno-libs-private but it is not installed
 libreoffice-sdbc-mysql : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                          Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                          Depends: libuno-sal3 (>= 4.2.0~rc1) but it is not installed
                          Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                          Depends: uno-libs-private but it is not installed
 libreoffice-sdbc-postgresql : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                               Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
                               Depends: libuno-sal3 (>= 4.1.0~alpha) but it is not installed
                               Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                               Depends: uno-libs-private but it is not installed
 libreoffice-writer : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
                      Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
                      Depends: libuno-sal3 (>= 5.3.0~alpha) but it is not installed
                      Depends: libuno-salhelpergcc3-3 (>= 1.4.0) but it is not installed
                      Depends: uno-libs-private but it is not installed
                      Breaks: libreoffice-common (< 1:6.4.2~rc1~) but 1:6.3.5~rc2-0ubuntu0.18.04.1~lo1 is installed
 python3-uno : Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
               Depends: libuno-cppuhelpergcc3-3 (>= 5.3.0~alpha) but it is not installed
               Depends: libuno-sal3 (>= 5.4.0~alpha) but it is not installed
               Depends: libuno-salhelpergcc3-3 (>= 3.6.0~beta) but it is not installed
               Depends: uno-libs-private but it is not installed
 ure : Depends: uno-libs-private (= 1:6.4.2-0ubuntu0.18.04.2) but it is not installed
       Depends: libuno-cppu3 (>= 4.4.0~alpha) but it is not installed
       Depends: libuno-cppuhelpergcc3-3 (>= 4.0.0~alpha) but it is not installed
       Depends: libuno-purpenvhelpergcc3-3 (>= 1.4.0) but it is not installed
       Depends: libuno-sal3 (>= 5.3.0~alpha) but it is not installed
       Depends: libuno-salhelpergcc3-3 (>= 3.6.0~beta) but it is not installed
       Recommends: libjuh-java but it is not installed
       Recommends: libjurt-java but it is not installed
       Recommends: libridl-java but it is not installed
       Recommends: libunoloader-java but it is not installed

**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: ________

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by gherrarte** [comment]
Sorry.   I found your advice.  I will do as you suggested already.  Thanks

**Comment by dominichayesferen** [comment]
#14
