### ISSUE TITLE
''Boost Python error in job 'packages'.''

### ISSUE THREAD

**Issue by Joarell** [feren-OS/Feren-OS-Dependency-Issue-Reporting#16]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: Joseph Joarell

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```
![Screenshot_20200414_233151](https://user-images.githubusercontent.com/42722369/79293304-c3563100-7ea9-11ea-983a-1a3bbe6bb650.png)

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by dominichayesferen** [comment]
Wrong area to report it in, and also it should now be fixed so try again.

**Comment by Joarell** [comment]
Hi there!

I'm sorry for using the wrong area to report that issue.
However, thank you so much for your quick response!
Have a great day and stay safely!

Warmest regards from São Paulo!

Em qua., 15 de abr. de 2020 às 12:43, The feren OS Dev <
notifications@github.com> escreveu:
