### ISSUE TITLE
telegram-desktop has no installation candidate

### ISSUE THREAD

**Issue by naveens007** [feren-OS/Feren-OS-Dependency-Issue-Reporting#18]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: telegram-desktop

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 telegram-desktop : Depends: libavcodec57 but it is not installable or
                             libavcodec-extra57 but it is not installable
                    Depends: libavformat57 but it is not installable
                    Depends: libavutil55 but it is not installable
                    Depends: libswresample2 but it is not installable
                    Depends: libswscale4 but it is not installable
                    Depends: libtgvoip1.0.3 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by dominichayesferen** [comment]
Can no longer reproduce on 2020.11 after performing the steps on https://medium.com/feren-os/plasma-workspace-issue-fix-and-fix-methods-for-those-affected-36f3ddd81e96, so... 'fixed'.
