### ISSUE TITLE
Tried installing Playonlinux from store. It does not finish installation. My network is fine. 

### ISSUE THREAD

**Issue by ashokmaggu** [feren-OS/Feren-OS-Dependency-Issue-Reporting#19]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: _Playonlinux, and Wine 

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
``Installation isnt finished; it just hangs close to the end.

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by dominichayesferen** [comment]
This sounds like https://github.com/feren-OS/Bug-Reporting-Center/issues/182. Given the high likeliness of that, and that it successfully installs through Welcome Screen, I'mma therefore close this as 'duplicate'.
