### ISSUE TITLE
mintupdate system is broken 

### ISSUE THREAD

**Issue by terryglover** [feren-OS/Feren-OS-Dependency-Issue-Reporting#2]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: ________

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.
on start up this morning the update icon was missing from the panel, when trying to re-install from the store site it says package is broken and asking  to input  on terminal apt-get install-f
on closing down last night everything was working better than great, the update manager installed all the latest packages for this machine  please tell me how to cure this issue in non-technical langauge a newbie who has just installed the OS after traversing windows 3, 3.1, 5, XP, 7 and 8 so quite ancient

**Comment by dominichayesferen** [comment]
Go into Terminal and then put the following in the Terminal window (copy and paste):
`pkexec apt-get -f install`

**Comment by terryglover** [comment]
Many Thanks, system back up and running very smoothly,however, i have
another very slight query, one of the recomended updats last week allowed
system to start up quicker by reading upfront pages, i have a , its
annoying and locks system sometimes, how do i remove this package?problem
in that it reads the system keyring and loads it onto page before system is
fully loaded
Terry Glover

**Comment by dominichayesferen** [comment]
Which package?

**Comment by terryglover** [comment]
Good morning and thank you for your prompt response. Unfortunately I do not
know the name of the package the update manager installed, other than it
was a third party app and designed to speed up the start process.On start
up It loads the FEREN screen icon them login page(auto login) then the
system keyring followed by cursor then fully loads homepage.however the
keyring has no cursor and I have to press cancel then keyring comes back
with cursor to allow unlocking.i hope this makes sense to you.anyway.i do
not think it speeds up startup in any measurable way

terry glover

**Comment by dominichayesferen** [comment]
@terryglover Try clicking in the input box on the initial keyring dialog to gain the cursor, then?

**Comment by terryglover** [comment]
Many thanks for your prompt response.in relation to the keyring issue.it
does not allow me to click into cursor box, click into cancel or
authenticate either until desktop is fully loaded.then it accepts password,
although this is a very minor problem it does spoil what otherwise is a
great OS, just wish I could remove the download causing it
Thanks

terry glover

**Comment by dominichayesferen** [comment]
@terryglover Either wait for the desktop to load then or disable autologin, in that case...
