### ISSUE TITLE
When updating Plasma-Workspace feren-patched-kcmlookandfeel was removed

### ISSUE THREAD

**Issue by ghost** [feren-OS/Feren-OS-Dependency-Issue-Reporting#22]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: feren-patched-kcmlookandfeel________

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```jon@noodly-poe:~$ sudo apt install feren-patched-kcmlookandfeel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 feren-patched-kcmlookandfeel : Depends: plasma-workspace (>= 4:5.20.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by dominichayesferen** [comment]
This is intentional because of APT's stupid handling of package changes when upgrading plasma-workspace for so many people causing so many people rather severe package breakage issues. feren-patched-kcmlookandfeel was merged into plasma-workspace's own package.

**Comment by ghost** [comment]
> This is intentional because of APT's stupid handling of package changes when upgrading plasma-workspace for so many people causing so many people rather severe package breakage issues. feren-patched-kcmlookandfeel was merged into plasma-workspace's own package.

Ahhh okay, thank you :)
