### ISSUE TITLE
Missing Vivaldi Signing Key breaks switch from Cinnamon to Plasma

### ISSUE THREAD

**Issue by thequickbrownfox** [feren-OS/Feren-OS-Dependency-Issue-Reporting#23]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: Transition Package

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
**I can't copy paste, this happened on another machine. But add this at the start of your transition script, BEFORE apt-get update:**

```
wget -qO- http://repo.vivaldi.com/stable/linux_signing_key.pub | sudo apt-key add -
```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by dominichayesferen** [comment]
Should be fixed now. :crossed_fingers:
