### ISSUE TITLE
shutter

### ISSUE THREAD

**Issue by davidandmargaret** [feren-OS/Feren-OS-Dependency-Issue-Reporting#3]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: ________

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.
The problem with shutter is well known in that a couple of of important dependencies were removed by Ubuntu.. While Feron is a Mint spin, it would be nice to see goo:canvas and gnome-web-photo returned to our repo,as shutter is highlighted software.

**Comment by dominichayesferen** [comment]
Do you know about which packages that is?

**Comment by davidandmargaret** [comment]
The two packages are gnome-web-photo and libgoo-canvas-perl, which were
removed from the repo in ubuntu 18.04 Bionic Beaver .

This is an explanation of why it was removed:
https://www.linuxuprising.com/2018/10/shutter-removed-from-ubuntu-1810-and.html
A search by:  ./chob-linux shutter shows that nobody has taken up the
challenge yet of fixing this mess, but based on the number of articles on
the subject demonstrates the need.(despite the pages of workarounds)


D. W. Wagg
