### ISSUE TITLE
Any chance of getting a 22.04 based release this year?

### ISSUE THREAD

**Issue by Flashwalker** [feren-OS/Feren-OS-Dependency-Issue-Reporting#31]
20.04 release is outdated and some apps won't run any more.  
I'm unable to install my favorite applications on 20.04 due to outdated `libc6`.

Is there any chance of getting a 22.04 based release this year?
Or has this distro been abandoned?

**Comment by dominichayesferen** [comment]
https://ferenos.weebly.com/test-feren-os-202307.html
https://github.com/orgs/feren-OS/projects/11

Current Target: August 2023.

**Comment by Flashwalker** [comment]
@dominichayesferen 
Oh, very good news!

I posted here because I can't open the weebly site because of the blockage.

Good to know here.

**Comment by Flashwalker** [comment]
It looks abandoned, though.

**Comment by dominichayesferen** [comment]
https://medium.com/feren-os/feren-os-2023-07-will-be-delayed-further-to-august-or-september-a6cf98295b7f

Turns out I'm awful at deadlines... probably gonna have to extend this further delay into October just to ensure there's time for beta-testing.
