### ISSUE TITLE
Theme Sweet KDE, failed to install dependency

### ISSUE THREAD

**Issue by AlexCGI** [feren-OS/Feren-OS-Dependency-Issue-Reporting#32]
![Screenshot_20240614_131949](https://github.com/feren-OS/Dependency-Issue-Reporting/assets/12785584/5e1fbdd4-5066-40ae-b37f-f3dac5f436ff)

Hello everyone, I had FerenOS installed in a virtual machine, and when I installed a global theme 'Sweet Theme', it was installed correctly. Now that I have FerenOS installed natively on my PC, I have reinstalled the theme and I get the following dependency problem (image).
My route of the procedure is: System Settings/Appearance/Get New Global Themes/...theme 'Sweet KDE'.

Thank you for offering a pleasant and user-friendly OS.
Regards: Alexander Preciado

**Comment by dominichayesferen** [comment]
Your system is out of date - Feren OS already has a workaround for this since July 2023.
