### ISSUE TITLE
feren-ppas stalls on postinst

### ISSUE THREAD

**Issue by cranksV477** [feren-OS/Feren-OS-Dependency-Issue-Reporting#5]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: ________

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by cranksV477** [comment]
What is the name of the troublesome package?
Please put the name of the package here: feren ppas (amd64)

This upgrade stalls and when I open 'Details' to see what is happening, this is what I found...

Setting up feren-autoupdate-config (2019.06.0.0.0) ...

Configuration file '/etc/apt/apt.conf.d/50unattended-upgrades'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** 50unattended-upgrades (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/apt/apt.conf.d/50unattended-upgrades ...
W: Moving 50unattended-upgrades.dpkg-old to /tmp/
Setting up feren-ppas (2019.06.0.0.0) ...
grep: /etc/apt/sources.list.d/additional-repositories.list: No such file or directory
grep: /etc/apt/sources.list.d/additional-repositories.list: No such file or directory
grep: /etc/apt/sources.list.d/vivaldi.list: No such file or directory
grep: /etc/apt/sources.list.d/vivaldi.list: No such file or directory
Warning: The postinst maintainerscript of the package feren-ppas
Warning: seems to use apt-key (provided by apt) without depending on gnupg or gnupg2.
Warning: This will BREAK in the future and should be fixed by the package maintainer(s).
Note: Check first if apt-key functionality is needed at all - it probably isn't!
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package feren-ppas)
OK

I trust this is what you need to investigate this issue??  BTW I really enjoy your distro and it is by far my favourite!

**Comment by dominichayesferen** [comment]
Hmm... does it occur again when you try it again after force cancelling it and doing a `sudo dpkg --configure -a`?

**Comment by dominichayesferen** [comment]
Also this should be on https://github.com/feren-OS/Bug-Reporting-Center/issues/

**Comment by dominichayesferen** [comment]
It seems that from what I can get of the script's current point of execution based on output from you and looking at the script that was running in my view, 'add-apt-repository' ended up stalling on a repository...

Try running this in Terminal:
`sudo sh -c 'echo "#!/bin/bash" > /var/lib/dpkg/info/feren-ppas.postinst' && sudo apt update && sudo apt install --reinstall ferensources-ubuntu -y && sudo apt install --reinstall feren-ppas -y`

sudo password = Your Password

**Comment by cranksV477** [comment]
This is the result of your suggestion....

Setting up feren-ppas (2019.06.0.0.0) ...
grep: /etc/apt/sources.list.d/additional-repositories.list: No such file or
directory
grep: /etc/apt/sources.list.d/additional-repositories.list: No such file or
directory
grep: /etc/apt/sources.list.d/vivaldi.list: No such file or directory
grep: /etc/apt/sources.list.d/vivaldi.list: No such file or directory
Warning: The postinst maintainerscript of the package feren-ppas
Warning: seems to use apt-key (provided by apt) without depending on gnupg
or gnupg2.
Warning: This will BREAK in the future and should be fixed by the package
maintainer(s).
Note: Check first if apt-key functionality is needed at all - it probably
isn't!
Warning: apt-key should not be used in scripts (called from postinst
maintainerscript of the package feren-ppas)
OK

**Comment by cranksV477** [comment]
This is the output... looks like some packages cannot be updated?

Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease

Hit:3 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu
bionic InRelease
Ign:4 http://packages.linuxmint.com tessa InRelease

Hit:5 http://dl.google.com/linux/chrome/deb stable Release

Hit:6 http://packages.linuxmint.com tessa Release

Get:9 https://gitlab.com/feren-os/feren-repositories-neon/raw/master stable
InRelease [1,702 B]
Get:10
https://gitlab.com/feren-os/feren-repositories/raw/master/repositories
stable InRelease [8,525 B]
Err:11 http://archive.ubuntu.com/ubuntu bionic InRelease

  Connection failed [IP: 2001:67c:1560:8001::14 80]
Err:12 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Connection failed [IP: 2001:67c:1560:8001::14 80]
Err:13 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Connection failed [IP: 2001:67c:1360:8001::17 80]
Hit:14 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Fetched 10.2 kB in 2min 2s (83 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
27 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease
 Connection failed [IP: 2001:67c:1560:8001::14 80]
W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Connection
failed [IP: 2001:67c:1360:8001::17 80]
W: Failed to fetch
http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease
 Connection failed [IP: 2001:67c:1560:8001::14 80]
W: Some index files failed to download. They have been ignored, or old ones
used instead.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a'
to correct the problem.

**Comment by dominichayesferen** [comment]
@cranksV477 Try it again, you might've done it on the Launchpad Maintenance time.

**Comment by cranksV477** [comment]
Thanks feren...
Did it again and looks like it has stalled at 67%

Ign:1 http://mirror.internode.on.net/pub/linuxmint-packages tessa InRelease
Hit:2 http://mirror.internode.on.net/pub/linuxmint-packages tessa Release      
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:5 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu bionic InRelease
Hit:6 http://archive.canonical.com/ubuntu bionic InRelease                     
Get:7 https://gitlab.com/feren-os/feren-repositories-neon/raw/master stable InRelease [1,702 B]
Ign:8 http://dl.google.com/linux/earth/deb stable InRelease                    
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:11 http://dl.google.com/linux/earth/deb stable Release                     
Get:13 https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable InRelease [8,525 B]
Err:14 http://mirror.as24220.net/pub/ubuntu bionic InRelease                   
  Could not connect to mirror.as24220.net:80 (116.66.162.254), connection timed out
Err:15 http://mirror.as24220.net/pub/ubuntu bionic-updates InRelease        
  Unable to connect to mirror.as24220.net:http:
Err:16 http://mirror.as24220.net/pub/ubuntu bionic-backports InRelease
  Unable to connect to mirror.as24220.net:http:
Err:17 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Connection failed [IP: 2001:67c:1562::19 80]
Fetched 10.2 kB in 1min 1s (168 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://dl.google.com/linux/earth/deb stable InRelease' doesn't support architecture 'i386'
W: Failed to fetch http://mirror.as24220.net/pub/ubuntu/dists/bionic/InRelease  Could not connect to mirror.as24220.net:80 (116.66.162.254), connection timed out
W: Failed to fetch http://mirror.as24220.net/pub/ubuntu/dists/bionic-updates/InRelease  Unable to connect to mirror.as24220.net:http:
W: Failed to fetch http://mirror.as24220.net/pub/ubuntu/dists/bionic-backports/InRelease  Unable to connect to mirror.as24220.net:http:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Connection failed [IP: 2001:67c:1562::19 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  feren-backgrounds-vanadium libexiv2-26 libllvm7 linux-headers-4.18.0-21
  linux-headers-4.18.0-21-generic linux-headers-4.18.0-22
  linux-headers-4.18.0-22-generic linux-image-4.18.0-21-generic
  linux-image-4.18.0-22-generic linux-modules-4.18.0-21-generic
  linux-modules-4.18.0-22-generic linux-modules-extra-4.18.0-21-generic
  linux-modules-extra-4.18.0-22-generic
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 1 to reinstall, 0 to remove and 2 not to upgrade.
Need to get 152 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable/main amd64 ferensources-ubuntu all 2019.04.0.0.2 [152 kB]
Fetched 152 kB in 2s (88.3 kB/s)              
(Reading database ... 338002 files and directories currently installed.)
Preparing to unpack .../ferensources-ubuntu_2019.04.0.0.2_all.deb ...
Unpacking ferensources-ubuntu (2019.04.0.0.2) over (2019.04.0.0.2) ...
Setting up ferensources-ubuntu (2019.04.0.0.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23+linuxmint4) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  feren-backgrounds-vanadium libexiv2-26 libllvm7 linux-headers-4.18.0-21
  linux-headers-4.18.0-21-generic linux-headers-4.18.0-22
  linux-headers-4.18.0-22-generic linux-image-4.18.0-21-generic
  linux-image-4.18.0-22-generic linux-modules-4.18.0-21-generic
  linux-modules-4.18.0-22-generic linux-modules-extra-4.18.0-21-generic
  linux-modules-extra-4.18.0-22-generic
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 1 to reinstall, 0 to remove and 2 not to upgrade.
Need to get 4,440 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://gitlab.com/feren-os/feren-repositories/raw/master/repositories stable/main amd64 feren-ppas all 2019.06.0.0.0 [4,440 B]
Fetched 4,440 B in 1s (4,516 B/s)            
(Reading database ... 338002 files and directories currently installed.)
Preparing to unpack .../feren-ppas_2019.06.0.0.0_all.deb ...
Unpacking feren-ppas (2019.06.0.0.0) over (2019.06.0.0.0) ...
Setting up feren-ppas (2019.06.0.0.0) ...
/var/lib/dpkg/info/feren-ppas.postinst: 10: /var/lib/dpkg/info/feren-ppas.postinst: Bad substitution
/var/lib/dpkg/info/feren-ppas.postinst: 11: /var/lib/dpkg/info/feren-ppas.postinst: Bad substitution
/var/lib/dpkg/info/feren-ppas.postinst: 12: [: Illegal number: 
/var/lib/dpkg/info/feren-ppas.postinst: 14: [: Illegal number: 
/var/lib/dpkg/info/feren-ppas.postinst: 16: [: Illegal number: 
grep: /etc/apt/sources.list.d/additional-repositories.list: No such file or directory
grep: /etc/apt/sources.list.d/additional-repositories.list: No such file or directory
grep: /etc/apt/sources.list.d/vivaldi.list: No such file or directory
grep: /etc/apt/sources.list.d/vivaldi.list: No such file or directory
Warning: The postinst maintainerscript of the package feren-ppas
Warning: seems to use apt-key (provided by apt) without depending on gnupg or gnupg2.
Warning: This will BREAK in the future and should be fixed by the package maintainer(s).
Note: Check first if apt-key functionality is needed at all - it probably isn't!
Warning: apt-key should not be used in scripts (called from postinst maintainerscript of the package feren-ppas)
OK

Progress: [ 67%] [######################################....................]

**Comment by dominichayesferen** [comment]
@cranksV477 I've updated feren-ppas to 2019.07.0.0.0, at https://gitlab.com/feren-os/feren-repositories/raw/master/repositories/pool/main/f/feren-ppas/feren-ppas_2019.07.0.0.0_all.deb . Could you try installing that version of the package so that I can better see where it stalls for you?

**Comment by cranksV477** [comment]
Thanks feren...sadly this did not work either...'unable to initiate server'

**Comment by cranksV477** [comment]
Success!!  
By chance I checked the update manager and applied the updates and all is good!

Thanks for a great product and also for your time and effort in replying to my problem.

Regards
