### ISSUE TITLE
Latte-dock will not run

### ISSUE THREAD

**Issue by ghost** [feren-OS/Feren-OS-Dependency-Issue-Reporting#7]
Latte-dock seems to install ok but it will not run. The message says that the Gnome icon pack is not found.

**Comment by dominichayesferen** [comment]
Are you using Feren OS or Feren OS Next? Feren OS Next has Latte running at all times on the default and other Latte-using layouts.

**Comment by ghost** [comment]
I`m so sorry I jumped the gun. I am running Next RC1. I forgot about
choosing a configuration that includes it. I need to pay more attention.
Great job by the way.

**Comment by dominichayesferen** [comment]
Also BTW this is the wrong area given what you reported looks like it would be a **bug report**.
