### ISSUE TITLE
Transition problem

### ISSUE THREAD

**Issue by chacopa** [feren-OS/Feren-OS-Dependency-Issue-Reporting#8]
Hello!

First of all, thanks for the xmas present!

I´m trying to use the transition tool to migrate from Feren OS Classic.  The tool shows me a terminal, but stops the process with the following message:

ARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
gnome-themes-standard is already the newest version (3.28-1ubuntu1).
policykit-desktop-privileges is already the newest version (0.20ubuntu18.04.1).
onboard is already the newest version (1.4.1-2ubuntu1mint2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 plasma-pa : Depends: pulseaudio-module-gconf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Gtk-Message: 11:58:43.367: GtkDialog mapped without a transient parent. This is discouraged.

I opened Synaptic and checked the module pulseaudio-module-gconf for install and got the following message:

  Depends: libpulse0 (=1:11.1-1ubuntu7.4) but 1:11.1-1ubuntu7.5 is to be installed
 Depends: pulseaudio (= 1:11.1-1ubuntu7.4)

I then checked libpulse0 and saw that ubuntu7.5 is already installed.  If I choose to upgrade that module to the current version 7.4, it wants to uninstall a whole bunch of stuff, so I stopped.

The same scenario applies to the pulseaudio module.  Ubuntu 7.5 is installed and to upgrade to 7.4, a whole slew of stuff will be removed.

I am hesitant to proceed....any ideas?

Thanks!

**Comment by dominichayesferen** [comment]
I'll do a repository sync in a little bit. They might've fixed that upstream.

**Comment by dominichayesferen** [comment]
Try going in Software Sources -> Maintenance -> Downgrade Foreign Packages to see if the package is simply just a pulled release of a pulseaudio package.
