### ISSUE TITLE
xserver-xorg-input-wacom-hwe-18.04 

### ISSUE THREAD

**Issue by ratsalad** [feren-OS/Feren-OS-Dependency-Issue-Reporting#9]
**Make sure you have the default repository set in Feren OS**
If you have any other repositories enabled in Feren OS outside of the default set of repositories, then this might be the cause of your package's dependency issue.

**What is the name of the troublesome package?**
Please put the name of the package here: nohup: redirecting stderr to stdout
Installing the new Feren OS experience... This WILL take a while...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-input-wacom-hwe-18.04 : Depends: xserver-xorg-core-hwe-18.04 (>= 2:1.18.99.901) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  feren-backgrounds-xenon libvte-common libvte9 python-pycurl python-vte
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-input-wacom-hwe-18.04 : Depends: xserver-xorg-core-hwe-18.04 (>= 2:1.18.99.901) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Gtk-Message: 09:59:31.065: GtkDialog mapped without a transient parent. This is discouraged.

**What is the output of an apt-get install attempt for this package?**
Please copy and paste the output of apt-get install (troublesome package name here) below in the space between the two triple-`s:
```
nohup: redirecting stderr to stdout
Installing the new Feren OS experience... This WILL take a while...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-input-wacom-hwe-18.04 : Depends: xserver-xorg-core-hwe-18.04 (>= 2:1.18.99.901) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  feren-backgrounds-xenon libvte-common libvte9 python-pycurl python-vte
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xserver-xorg-input-wacom-hwe-18.04 : Depends: xserver-xorg-core-hwe-18.04 (>= 2:1.18.99.901) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Gtk-Message: 09:59:31.065: GtkDialog mapped without a transient parent. This is discouraged.

```

Thank you for helping me fix as many dependency issues as possible. When you're ready to report, click 'Submit new issue'. You can be contacted by The Developer or others via replies to this issue in the future, so please be sure to check GitHub Notifications during the time this issue is open, otherwise this issue could be closed due to inactivity from those suffering from this dependency issue.

**Comment by dominichayesferen** [comment]
When did you install Feren OS?

**Comment by dominichayesferen** [comment]
Try doing the transition again on the latest version of feren-cinn2plas.
